In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
n1 = np.array([1,2,3,4])

In [3]:
n1

array([1, 2, 3, 4])

In [4]:
n2 = np.array([[1,2,3,4],[5,6,7,8]])

In [5]:
n2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
type(n2)

numpy.ndarray

In [7]:
z = np.zeros((1,2))

In [8]:
z

array([[0., 0.]])

In [9]:
s = np.zeros((5,5))

In [10]:
s

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
f = np.full((5,5),160)

In [16]:
f

array([[160, 160, 160, 160, 160],
       [160, 160, 160, 160, 160],
       [160, 160, 160, 160, 160],
       [160, 160, 160, 160, 160],
       [160, 160, 160, 160, 160]])

In [20]:
n5 = np.arange(10,20)

In [22]:
n5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [25]:
n6 = np.arange(10,60,4)

In [26]:
n6

array([10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 54, 58])

In [29]:
n7 = np.random.randint(1,50,6)

In [30]:
n7

array([44, 41,  1,  5, 26, 34], dtype=int32)

In [32]:
n8 = np.array([[1,2,3,4],[5,6,7,8]])

In [35]:
n8.shape

(2, 4)

In [37]:
n8.shape = (4,2)
n8.shape

(4, 2)

In [40]:
#combine

n2 = np.array([1,2,3,4])
n3 = np.array([5,6,7,8])

In [41]:
np.vstack((n2,n3))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [42]:
np.hstack((n2,n3))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [44]:
np.column_stack((n2,n3))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [46]:
n9 = np.array([10,20,30,40,50,60])
n10 = np.array([50,60,70,80,90,40])

In [49]:
np.intersect1d(n9,n10)

array([40, 50, 60])

In [50]:
np.setdiff1d(n9,n10)

array([10, 20, 30])

In [51]:
np.setdiff1d(n10,n9)

array([70, 80, 90])

In [53]:
n11 = np.array([10,20])
n12 = np.array([30,40])

In [55]:
np.sum((n11,n12))

np.int64(100)

In [57]:
np.sum((n11,n12),axis = 0)

array([40, 60])

In [58]:
np.sum((n11,n12),axis = 1)

array([30, 70])

In [59]:
n13 = np.array([10,20,30,40])

In [61]:
np.median(n13)

np.float64(25.0)

In [63]:
np.mean(n13)

np.float64(25.0)

In [64]:
np.std(n13)

np.float64(11.180339887498949)

In [65]:
n1

array([1, 2, 3, 4])

In [66]:
np.save("myarray", n1)

In [68]:
new_n1 = np.load("myarray.npy")

In [69]:
new_n1

array([1, 2, 3, 4])